# Generated by Django 5.0.4 on 2024-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbdbdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nalja', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='forecastData',
        ),
    ]
