# Generated by Django 5.0.4 on 2024-04-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_forecastdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dbdbdb',
        ),
    ]
