# Generated by Django 5.0.4 on 2024-04-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_dbdbdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdata',
            name='category',
        ),
    ]
