# Generated by Django 5.0.4 on 2024-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_question_forecastdata_fnx_forecastdata_fny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdata',
            name='fnx',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='forecastdata',
            name='fny',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rainpercent',
            name='fnx',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rainpercent',
            name='fny',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='wind',
            name='fnx',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='wind',
            name='fny',
            field=models.CharField(max_length=5),
        ),
    ]
