# Generated by Django 5.0.4 on 2024-04-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_forecastdata_fnx_alter_forecastdata_fny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdata',
            name='index_num',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='forecastdata',
            name='indexname',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='rainpercent',
            name='index_num',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='rainpercent',
            name='indexname',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='wind',
            name='index_num',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='wind',
            name='indexname',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
